name = "my-mirror-app"     # 프로젝트 이름 (원하는 이름으로 변경 가능)
main = "assets/js/mirror.js"
compatibility_date = "2025-09-18"

[site]
bucket = "./"              # root 디렉토리를 기준으로 배포
entry-point = "workers-site"

[build]
command = ""

[env.production]
workers_dev = true
